config/routes.rb
AlecTutorManager::Application.routes.draw do
  resources :reviews

  resources :tutors do
    member do
      get 'check_in_toggle', :as => :check_in_toggle
      get 'increment_currently_tutoring', :as => :increment_tutoring
      get 'decrement_currently_tutoring', :as => :decrement_tutoring
    end
    collection { post :import }
  end

  resources :courses do
    collection {
      post :import
      get :tutorsched
    }
  end

  devise_for :users

  root :to => 'courses#index'
end

app/models/tutor.rb
require_dependency 'timespan'

class Tutor < ActiveRecord::Base
  attr_accessible :status, :email, :name, :room, :checked_in, :course_ids, :schedule, :course_numbers, :timespans
  # attr_accessor :course_numbers
  validates_presence_of :name

  # {0: [{start: Time, stop: Time}, {start: Time, stop: Time}], 1: ['1-2']}
  serialize :schedule, Hash

  has_and_belongs_to_many :courses
  after_initialize :assign_default_values

  # used as shortcut when creating records
  def course_numbers=(course_nums)    
    # remove all current course associations
    courses.delete_all

    course_nums.each{|course_num|
      course = Course.find_or_create_by_course_number(course_num.strip)
      courses << course
    }
    save
  end

  # for form helper
  def timespans
    schedule.values.join(', ')
  end

  # parses an array like:
  # ["M 1-2", "W 3-4"]
  def timespans=(timespans)
    timespans = timespans.split(',').map(&:strip) if timespans.class == String
    
    timespans.map!{|t|
      Timespan.parse(t)
    }
    self.schedule = Timespan.by_day(timespans)
  end

  def names
    name.split(' ')
  end

  def is_available?
    checked_in
  end

  def tutors_on?(day)
    day_code = (day.to_i == day ? day : DateTime.parse(day.to_s).wday)
    !schedule[day_code].nil?
  end

  def timespan_today
    schedule[Date.today.wday]
  end

  def full_schedule
    schedule.values.flatten.join ", "
  end

  # def should_be_here?
    # now = Time.now
    # schedule_start < now && now < schedule_end
  # end

  def self.to_csv
    CSV.generate do |csv|
      columns = %w(name schedule courses)
      csv << columns
      all.each do |tutor|
        # csv << tutor.attributes.values_at(*column_names)
        values = [tutor.name]
        values << tutor.schedule.values.join(", ")
        values << tutor.courses.join(", ")
        csv << values
      end
    end
  end

  def self.import(file)
    keys = nil
    students = {}

    spreadsheet = open_spreadsheet(file)
    # binding.pry
    # use the "ALL" sheet
    spreadsheet.default_sheet = spreadsheet.sheets.find{|sheet| /website/i =~ sheet}

    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      course = Hash[[header, spreadsheet.row(i)].transpose]
      student = {}
      student[:name] = "#{course['First Name']} #{course['Last Name']}"

      # get the schedule
      student[:schedule] = {}
      %w(Sunday Monday Tuesday Wednesday Thursday Friday).each_with_index{|day, i|
        span = course[day]
        student[:schedule][i] = Timespan.parse("#{day} #{span}") if span
      }

      # get the course numbers
      student[:course_numbers] = []
      
      # save or find the temporary record
      students[student[:name]] ||= student

      # add the course
      # excel adds a decimal to numbers?
      course_num = course['Course Number'].to_s.gsub(".0", '')
      course_num = "#{course['Course']} #{course_num}"
      students[student[:name]][:course_numbers] << course_num
    end
    # puts students.to_yaml
    # raise 'lol'

    # now we have a `students` hash with all our data
    # time to perminantly update the records

    students.each{|name, student_data|
      student = Tutor.find_or_create_by_name(name)
      student.update_attributes(student_data)
    }
  end

  private

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Csv.new(file.path, nil, :ignore)
    when ".xls" then Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end

  def assign_default_values  
    self.room ||= %w(202N 202R 202K 202U 202T 202V CONFERENCE).sample

    # start 2-7pm 
    # self.schedule_start ||= Time.parse("#{2 + rand(3)}pm")
    # self.schedule_end ||= self.schedule_start + (2 + rand(4)).hours
  end
end

app/controllers/tutors_controller.rb
class TutorsController < ApplicationController
  before_filter :authenticate_user!
  layout :get_layout

  def check_in_toggle
    @tutor = Tutor.find(params[:id])
    
    @tutor.update_attribute(:checked_in, !@tutor.checked_in)
    redirect_to :back
  end

  def import
    Tutor.import(params[:file])
    redirect_to tutors_url, notice: 'Tutor data updated'
  end

  # GET /tutors
  # GET /tutors.json
  def index
    @tutors = Tutor.all.sort_by{|t|
      # first, last = t.name.split(" ")
      # last ? last : first
      span = t.timespan_today
      span ? span : Timespan.new
    }

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tutors }
      # format.csv { render csv: @tutors }
      format.csv { render text: Tutor.to_csv }
    end
  end

  # GET /tutors/1
  # GET /tutors/1.json
  def show
    @tutor = Tutor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tutor }
    end
  end

  # GET /tutors/new
  # GET /tutors/new.json
  def new
    @tutor = Tutor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tutor }
    end
  end

  # GET /tutors/1/edit
  def edit
    @tutor = Tutor.find(params[:id])
  end

  # POST /tutors
  # POST /tutors.json
  def create
    @tutor = Tutor.new(params[:tutor])

    respond_to do |format|
      if @tutor.save
        format.html { redirect_to tutors_path, notice: 'Tutor was successfully created.' }
        format.json { render json: @tutor, status: :created, location: @tutor }
      else
        format.html { render action: "new" }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tutors/1
  # PUT /tutors/1.json
  def update
    @tutor = Tutor.find(params[:id])

    respond_to do |format|
      if @tutor.update_attributes(params[:tutor])
        format.html { redirect_to :back, notice: 'Tutor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutors/1
  # DELETE /tutors/1.json
  def destroy
    @tutor = Tutor.find(params[:id])
    @tutor.destroy

    respond_to do |format|
      format.html { redirect_to tutors_url }
      format.json { head :no_content }
    end
  end

  private

  def get_layout
    request.xhr? ? false : 'application'
  end
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/views/tutors/_form.html.erb
<%= form_for @tutor, :html => {:class => "form-horizontal"} do |f| %>
  <% if @tutor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tutor.errors.count, "error") %> prohibited this tutor from being saved:</h2>

      <ul>
      <% @tutor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :email %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :timespans, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :timespans %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :checked_in, :class => "control-label" %>
    <div class="controls">
      <%= f.check_box :checked_in %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :status, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :status %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :room, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :room %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :course_ids, "Courses", :class => "control-label" %>
    <div class="controls">
      <%= f.collection_select :course_ids, Course.order(:name), :id, :name, {}, {:class => 'chzn-select', '
      data-placeholder' => "type to search for courses", :multiple => true} %>
      <br />
      <br />
      <%= f.submit :class => 'btn' %>
    </div>
  </div>
<% end %>

app/views/tutors/edit.html.erb
<h1>Editing tutor</h1>

<%= render 'form' %>

<%= link_to 'Show', @tutor %> |
<%= link_to 'Destroy', @tutor, method: :delete, data: { confirm: 'Are you sure?' } %> | 
<%= link_to 'Back', tutors_path %>

app/views/tutors/index.html.erb
<div id="buttons">
<%= link_to '<i class="icon-user"></i> New Tutor'.html_safe, new_tutor_path, class: 'btn' %> 
| 
<%= link_to '<i class="icon-download"></i> Download .csv'.html_safe, tutors_path(format: 'csv'), class: 'btn' %> 
|
<!-- todo: make this prettier with http://duckranger.com/2012/06/pretty-file-input-field-in-bootstrap/ or http://viget.com/inspire/custom-file-inputs-with-a-bit-of-jquery -->
<%= form_tag import_tutors_path, multipart: true, style: 'display:inline' do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Upload .csv or .xlxs", :class => 'btn' %>
<% end %>
</div>

<br />
<br />

<table class="table table-striped table-bordered">
  <tr>
    <th>Tutor</th>
    <th style="width: 100pt">
      Scheduled Time
      <div id="filter_day">
        <label class="checkbox inline">
          <%= check_box_tag :mon %>M
        </label>
        <label class="checkbox inline">
          <%= check_box_tag :tue %>Tu
        </label>
        <label class="checkbox inline">
          <%= check_box_tag :wed %>W
        </label>
        <label class="checkbox inline">
          <%= check_box_tag :thu %>Th
        </label>
        <label class="checkbox inline">
          <%= check_box_tag :fri %>F
        </label>
        <label class="checkbox inline">
          <%= check_box_tag :sat %>Sa
        </label>
        <label class="checkbox inline">
          <%= check_box_tag :sun %>Su
        </label>
        <%= button_tag 'today', {id: 'today', class: 'btn btn-mini'} %>
      </div>
    </th>
    <th>Courses</th>
    <th class="room">Room</th>
    <th class="status">Status</th>
  </tr>

<% @tutors.each do |tutor| %>
  <tr class="<%= tutor.schedule.values.flatten.map(&:day).map(&:downcase).join(' ') %>">
    <td><%= link_to tutor.name, edit_tutor_path(tutor) %></td>
    <td>
      <!-- I don't like this implementation -->
      <% days = %w(Sun Mon Tue Wed Thu Fri Sat) %>
      <% tutor.schedule.each do |day_code, timespan| %>
        <%# TODO: DON'T DO THIS. Fix the representation of timespan as arary always %>
        <% timespan = timespan.first if timespan.respond_to? :first %>
        <div class="<%= timespan.day.downcase %>">
          <span class="label <%= timespan.is_today? ? 'label-info' : ''%>"><%= timespan.day %>:</span>

          <%= timespan.span %>
        </div>
        <!-- label-success/info for current day -->
      <% end %>
    </td>
    <td>
      <% tutor.courses.each_with_index do |course, i| %>
        <%= link_to course.course_number, course %><%= ", " unless i == tutor.courses.size - 1 %>
      <% end %>
    </td>
    <td class="room">
      <%= form_for tutor do |f| %>
        <% if tutor.checked_in %>
          <%= tutor.room %>
        <% else %>
          <%= f.text_field :room %>
        <% end %>
        <%= f.hidden_field :checked_in, :value => !tutor.checked_in %>
        <%= f.submit "clock #{tutor.checked_in ? 'out' : 'in'}", :class => "btn" %>
      <% end %>
    </td>
    <td class="status">
      <div style="width: 10pt">
        <%= tutor.status %>
        <% if user_signed_in? %>
        <% else %>
        <% end %>
      </div>
    </td>
  </tr>
<% end %>
</table>

app/views/tutors/new.html.erb
<h1>New tutor</h1>

<%= render 'form' %>

<%= link_to 'Back', tutors_path %>

app/views/tutors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tutor.name %>
</p>

<p>
  <b>Schedule start:</b>
  <%= @tutor.schedule_start %>
</p>

<p>
  <b>Schedule end:</b>
  <%= @tutor.schedule_end %>
</p>

<p>
  <b>Capacity:</b>
  <%= @tutor.capacity %>
</p>

<p>
  <b>Status:</b>
  <%= @tutor.status %>
</p>

<p>
  <b>Room:</b>
  <%= @tutor.room %>
</p>

<p>
  <b>Email:</b>
  <%= @tutor.email %>
</p>


<%= link_to 'Edit', edit_tutor_path(@tutor) %> |
<%= link_to 'Back', tutors_path %>