config/routes.rb
AlecTutorManager::Application.routes.draw do
  resources :reviews

  resources :tutors do
    member do
      get 'check_in_toggle', :as => :check_in_toggle
      get 'increment_currently_tutoring', :as => :increment_tutoring
      get 'decrement_currently_tutoring', :as => :decrement_tutoring
    end
    collection { post :import }
  end

  resources :courses do
    collection {
      post :import
      get :tutorsched
    }
  end

  devise_for :users

  root :to => 'courses#index'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  layout :get_layout
  before_filter :authenticate_user!, :except => [:index, :show, :tutorsched]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all(:joins => :tutors).uniq.sort_by{|c| c.course_number}

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courses }
    end
  end

  def tutorsched
    @courses = Course.all(:joins => :tutors).uniq.sort_by{|c| c.course_number}
    @departments = {}
    @courses.each{|course|
      @departments[course.department] ||= []
      @departments[course.department] << course
    }
    render layout: false
  end

  def import
    Course.import(params[:file])
    redirect_to courses_url, notice: 'Course data updated'
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.json
  def new
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(params[:course])

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created, location: @course }
      else
        format.html { render action: "new" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    @course = Course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

  private

  def get_layout
    request.xhr? ? false : 'application'
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn' %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<!-- <h1>Editing course</h1>
 -->
<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.haml
-if user_signed_in?
  #buttons
  =link_to '<i class=""></i> New Course'.html_safe, new_course_path, class: 'btn'

  / <%#= form_tag import_courses_path, multipart: true, style: 'display:inline' do %>
  /   <%#= file_field_tag :file %>
  /   <%#= submit_tag "Upload .json", :class => 'btn btn-warning' %>
  / <%# end %>
  %br


%table(class="table table-striped table-bordered")
  %tr
    %th(style="width: 30%") Course
    %th(style="width: 100pt") Scheduled Times
    -# if user_signed_in?
      %th Tutors

  - @courses.each do |course|
    %tr
      %td= link_to course, course
      %td
        / I don't like this implementation
        %table.week.table.table-condensed
          %tr
            - today = Time.new.strftime('%a')
            - timespans = Timespan.by_day(course.scheduled_time)
            - %w(Sun Mon Tue Wed Thu Fri Sat).each_with_index do |day, i|
              %th{class: (day == today ? 'today' : '')}=day
          %tr
            - %w(Sun Mon Tue Wed Thu Fri Sat).each_with_index do |day, i|
              %td
                = timespans[i].map(&:span).join(', ') if timespans[i]

        - if user_signed_in?
          - Timespan.by_day(course.scheduled_time).each do |day_code, timespans|
            .tutors_by_day{class: timespans.first.day}
              - tutors = course.tutors.select{|t| t.tutors_on?(day_code)}.sort_by{|t| t.schedule[day_code]}
              - tutors.each do |tutor|
                - if tutor.schedule[day_code]
                  .tutor_name
                    - timespan = tutor.schedule[day_code]
                    -# TODO: FIX THIS AWFUL HACK by making tutor schedules hold arrays in their days instead of single timespans
                    - timespan = timespan.first if timespan.respond_to? :first
                    %span{class: 'label ' + (timespan.is_now? ? 'label-info' : '')}= timespan.to_s
                    = tutor.name

        -#%ul
          - Timespan.by_day(course.scheduled_time).each do |day_code, timespans|
            %li.course_day_time
              %span{class: "label " + (timespans.first.is_today? ? 'label-info' : '')}
                = timespans.first.day

              = timespans.map(&:span).join(', ')
              - if user_signed_in?
                .tutor_day_breakdown
                  - tutors = course.tutors.select{|t| t.tutors_on?(day_code)}.sort_by{|t| t.schedule[day_code]}
                  - tutors.each do |tutor|
                    - if tutor.schedule[day_code]
                      .tutor_name
                        - timespan = tutor.schedule[day_code]
                        -# TODO: FIX THIS AWFUL HACK by making tutor schedules hold arrays in their days instead of single timespans
                        - timespan = timespan.first if timespan.respond_to? :first
                        %span{class: 'label ' + (timespan.is_now? ? 'label-info' : '')}= timespan.span
                        = tutor.name

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<h2>
  <%= @course.to_s %> 
  <% if user_signed_in? %>
    <small class="muted"><%= link_to 'edit', edit_course_path(@course) %></small>
  <% else %>
    <small class="muted">
      <%= link_to "Leave Review", new_review_path("subject" => @course.name), :class => "btn" %>
    </small>
  <% end %>
</h2>

<table class="table table-striped table-bordered">
  <tr>
    <th>Tutor</th>
    <th>Status</th>
    <th>Scheduled Time</th>
    <% if user_signed_in? %>
      <th>Room</th>
      <th></th>
    <% end %>
  </tr>

<% @course.tutors.each_with_index do |tutor, i| %>
  <tr>
    <td>
      <% if user_signed_in? %>
        <%= link_to tutor.name, edit_tutor_path(tutor) %>
      <% else %>
        Tutor <%= i+1 %>
      <% end %>
    </td>
    <td>
      <div class="" style="width: 10pt">
        <%= tutor.status %>
        <% if user_signed_in? %>
        <% else %>
        <% end %>
      </div>
    </td>
    <td><%= tutor.full_schedule %></td>
    <%= form_for tutor do |f| %>
      <td>
        <% if tutor.checked_in %>
          <%= tutor.room %>
        <% else %>
          <%= f.text_field :room %>
        <% end %>
      </td>
      <td>
        <%= f.hidden_field :checked_in, :value => !tutor.checked_in %>
        <%= f.submit "clock #{tutor.checked_in ? 'out' : 'in'}", :class => "btn" %>
      </td>
    <% end if user_signed_in? %>
  </tr>
<% end %>
</table>

<br />
<% if user_signed_in? %>
  <%= link_to 'New Course', new_course_path %>
<% end %>

app/views/courses/tutorsched.html.haml
-@departments.each do |dept, courses|
  %p 
    %strong= dept + ":"
  %p
    -courses.each do |course|
      %strong(style="margin-left: 35px")=course.course_number + ":"
      =course.scheduled_time.join ", "
      %br
  -if dept == "MATH"
    %p NOTE: An important source of help for first-year math is the Math Help Room, 225 Clements, 4:30-7:30 PM Monday through Thursday!
  -if dept == "CSE"
    %p NOTE: An important source of help for CSE is the CSE Help Desk. Click <a href="Fall_2012_HelpDeskSchedule.pdf"> here </a> to see the  Spring 2013 schedule.<br>