config/routes.rb
AlecTutorManager::Application.routes.draw do
  resources :reviews

  resources :tutors do
    member do
      get 'check_in_toggle', :as => :check_in_toggle
      get 'increment_currently_tutoring', :as => :increment_tutoring
      get 'decrement_currently_tutoring', :as => :decrement_tutoring
    end
    collection { post :import }
  end

  resources :courses do
    collection {
      post :import
      get :tutorsched
    }
  end

  devise_for :users

  root :to => 'courses#index'
end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
      %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}
        %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
          %title= (content_for?(:title) ? yield(:title) + " | " : '') + "ALEC Tutor Manager"
          = csrf_meta_tags
          / Le HTML5 shim, for IE6-8 support of HTML elements
          /[if lt IE 9]
            <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
          = stylesheet_link_tag "application", :media => "all"
  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => "/", :style => "position: relative; padding-left: 40px"}
            =image_tag "logo.png", :style => "max-height: 50px; float: left; position: absolute; left: -10px; top: 5px"
            ALEC Tutors
          .container-fluid.nav-collapse
            %ul.nav.pull-right
              -unless user_signed_in?
                %li= link_to "Leave Review", new_review_path
                %li= link_to "Login", new_user_session_path
              -else
                %li= link_to current_user.email, edit_user_registration_path
                %li= link_to "Logout", destroy_user_session_path, :method => "DELETE"
          / /.nav-collapse
    .container-fluid
      .row-fluid
        .span12
          - if user_signed_in?
            %ul(class="nav nav-tabs")
              %li{:class => params[:controller]=="courses" ? "active" : ""}
                = link_to "Classes", courses_path
              %li{:class => params[:controller]=="tutors" ? "active" : ""}
                = link_to "Tutors", tutors_path
              %li{:class => params[:controller]=="reviews" ? "active" : ""}
                = link_to "Reviews", reviews_path
          = bootstrap_flash
          = yield
      / /row
      %footer
        %p © Mustang Developers 2012
    / /container
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"